### ISSUE TITLE
customize columns modal doesnt open

### ISSUE THREAD

**Issue by matthew-james** [onijim/owl-table#70]
Since updating recently (not sure what revision) the customize columns modal does not open.  service.customizeColumns is called but the modal is never rendered.

Am I missing a dependency or something?

**Comment by onijim** [comment]
I have spent hours and hours trying to figure this out on your demo site.  My thoughts were it was because of the old jQuery version or some conflict from vendor.min.js.

I replaced your include of vendor.min.js with a big list of the bower_components to try and avoid conflicts from the rest of Focus' javascript.  Still nothing.  I removed everything but the basic modal call and it is still broken.  It looks like something is interfering with and breaking the $modal service from angular-bootstrap.

I've moved dependencies, switched versions, etc etc and nothing is fixing it so far.  I've gone through the angular-bootstrap js file and put comments everywhere to do some debugging, and that was fruitless as well.

The kicker is, $modal works fine for Robert in IEP and he loads all the generic Focus javascript as well.

I am at a loss here.  I did a bit of experimenting with moving away from angular-bootstrap and using another modal, but all the other ones suck and make it a giant pain in the ass to do what angular-bootstrap made so easy.

Also it works perfectly fine on my own demo page - I tried screwing around with old versions of libraries on there and it still worked.

:(
